In [1]:
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

In [2]:
driver = webdriver.Chrome('C:/chromedriver/chromedriver.exe')

In [3]:
driver.get('http://statisticstimes.com/')

In [4]:
economy=driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]")
economy.click()

In [5]:
india=driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/div/a[3]").get_attribute('href')
driver.get(india)

In [6]:
gdp_statewise=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a").get_attribute('href')
driver.get(gdp_statewise)

In [7]:
fund_dict = {}
fund_dict['state'] = []
fund_dict['gsdp_19_20'] = []
fund_dict['gsdp_18_19'] = []
fund_dict['share'] = []
fund_dict['GDP'] = []
fund_dict['gsdp_19_20 at 2011_2012']=[]
fund_dict['gsdp_18_19 at 2011_2012']=[]

In [8]:
for i in range(1,20):
    r_tag = driver.find_elements_by_xpath('//*[@id="table_id"]/tbody/tr[1]/td[2]'.format(i))
    for d in r_tag:
        fund_dict['state'].append(d.text)

    # gsdp_19_20
    sn = driver.find_elements_by_xpath('//*[@id="table_id"]/tbody/tr[1]/td[3]'.format(i))
    for n in sn:
        fund_dict['gsdp_19_20'].append(n.text)
    
    # gsdp_18_19
    ind = driver.find_elements_by_xpath('//*[@id="table_id"]/tbody/tr[1]/td[4]'.format(i))
    for z in ind:
        fund_dict['gsdp_18_19'].append(z.text)
    
    # share
    sv = driver.find_elements_by_xpath('//*[@id="table_id"]/tbody/tr[1]/td[5]'.format(i))
    for s in sv:
        fund_dict['share'].append(s.text)

    # GDP
    loc = driver.find_elements_by_xpath('//*[@id="table_id"]/tbody/tr[1]/td[6]'.format(i))
    for l in loc:
        fund_dict['GDP'].append(l.text)
    
    # gsdp_19_20 at 2011_2012
    inv = driver.find_elements_by_xpath('//*[@id="table_id"]/tbody/tr[1]/td[7]'.format(i))
    for n in inv:
        fund_dict['gsdp_19_20 at 2011_2012'].append(n.text)
    
    gsdp = driver.find_elements_by_xpath('//*[@id="table_id"]/tbody/tr[1]/td[8]'.format(i))
    for m in gsdp:
        fund_dict['gsdp_18_19 at 2011_2012'].append(m.text)
    
fund_df = pd.DataFrame(fund_dict)
fund_df

,state,gsdp_19_20,gsdp_18_19,share,GDP,gsdp_19_20 at 2011_2012,gsdp_18_19 at 2011_2012
0,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
1,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
2,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
3,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
4,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
5,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
6,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
7,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
8,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
9,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
10,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
11,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
12,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
13,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
14,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
15,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
16,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
17,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"
18,Maharashtra,-,"2,632,792",13.88%,398.145,-,"2,039,074"

In [13]:
i am not noy able to scrape the list below the one row and column

'-'