In [1]:
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

In [2]:
driver = webdriver.Chrome('C:/chromedriver/chromedriver.exe')

In [3]:
driver.get('https://www.naukri.com/')

In [4]:
recruiter=driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/ul[1]/li[2]/a').get_attribute('href')
driver.get(recruiter)

In [5]:
search=driver.find_element_by_xpath('//input[@class="sugInp"]')
search.send_keys('data science')

In [6]:
button=driver.find_element_by_xpath('//button[@class="fl qsbSrch blueBtn"]')
button.click()

In [7]:
hr_name=[]
designation=[]
company=[]
location=[]
skill_i_hire_for=[]

s_tag=driver.find_elements_by_xpath("//span[@class='fl ellipsis']")
for s in s_tag:
    hr_name.append(s.text)

a_tag=driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
for a in a_tag:
    designation.append(a.text)
    
lastw_tag=driver.find_elements_by_xpath("//p[@class='highlightable']/a[2]/i")
for k in lastw_tag:
    company.append(k.text)
    
p_tag=driver.find_elements_by_xpath("//small[@class='ellipsis']")
for p in p_tag:
    location.append(p.text)
    
w_tag=driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
for w in w_tag:
    skill_i_hire_for.append(w.text)

In [8]:
print(len(hr_name))
print(len(designation))
print(len(company))
print(len(location))
print(len(skill_i_hire_for))

50
50
50
48
50

In [9]:
dict1 = {}
dict1['HR NAME']=hr_name[0:48]
dict1['DESIGNATION']=designation[0:48]
dict1['COMPANY NAME']=company[0:48]
dict1['LOCATION']=location[0:48]
dict1['SKILLS REQUIRED']=skill_i_hire_for[0:48]
df = pd.DataFrame(dict1)
df

,HR NAME,DESIGNATION,COMPANY NAME,LOCATION,SKILLS REQUIRED
0,Aakash Harit,HR Manager,,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,Talent Acquisition Executive,Recruitment Professional,,Chandigarh,"Web Designing, html5, Angular.js, seo, hadoop,..."
3,Anik Agrawal,Company Recruiter,,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,MARSIAN Technologies LLP,Company HR,,Pune,"Data Science, Artificial Intelligence, Machine..."
5,subhas patel,Founder CEO,,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
6,Jitendra Singh,Manager- Talent Acquisition,,Delhi,"Python, Data Science, .Net, Java, Big Data, Da..."
7,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
8,Institute for Financial Management and Resear,Programme Manager,,Chennai,Data Science
9,Balu Ramesh,HR Administrator,,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
10,Asif Lucknowi,Director,,Indore,"Technical Training, Software Development, Pres..."
11,InstaFinancials,Human Resource,,Bengaluru / Bangalore,"Software Development, It Sales, Account Manage..."
12,Kalpana Dumpala,Executive Hiring,,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
13,Mubarak,Company HR,,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
14,Kushal Rastogi,Company HR,,Mumbai,"Office Administration, Hr Administration, tele..."
15,Manisha Yadav,HR Executive,,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
16,Kapil Devang,HR Manager,,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
17,Riya Rajesh,Manager Talent Acquisition,,Cochin,Data Science
18,Mahesh Babu Channa,HR Team Lead,,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
19,Rashmi Bhattacharjee,HR Head,,Delhi,"Corporate Sales, Software Development, Softwar..."
20,Faizan Kareem,HR MANAGER,,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
21,Rithika dadwal,HR Recruiter,,Pune,"Data Science, Machine Learning, Python, R, Dee..."
22,Azahar Shaikh,Company Recruiter,,Pune,"Data Science, Artificial Intelligence, Machine..."
23,Sandhya Khandagale,HR Recruiter,,Pune,"Big Data, Data Science, Artificial Intelligenc..."
24,Shaun Rao,Manager Human Resources,,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
25,Dhruv Dev Dubey,Company Recruitment Head,,Bengaluru / Bangalore,"Server Administartion, Verilog, Vhdl, Digital ..."
26,Manas,Lead Talent acquisition,,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
27,kumar,Proprietor,,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
28,Sunil Vedula,CEO,,Delhi,"Signal Processing, Machine Learning, Neural Ne..."
29,Rajat Kumar,Founder CEO,,Mysoru / Mysore,"Web Technologies, Project Management, Software..."
30,Jayanth N,Project Manager,,Noida,"Data Analytics, Managed Services, Team Leading..."
31,Prateek Kumar,Head,,New Delhi,"Java, Python, Angularjs, Software Testing, Mac..."
32,Amit Sharma,Consultant,,Chennai,"Machine Learning, Artificial Intelligence, Dat..."
33,Kanan,senior technology instructor,,Aligarh,"C, C++, Artificial Intelligence, Python, Php, ..."
34,Shashikant Chaudhary,HR Recruiter/HR Excutive,,Salt Lake City,"Relationship Management, Retail Sales, Private..."
35,Brad,"Manager, Technical Recruiting",,Pune,"Data Science, Software Engineering"
36,Rutuja Pawar,Technical Recruiter,,Bengaluru / Bangalore,"Data Science, Big Data Analytics, Digital Mark..."
37,Madhusudhan Sridhar,Erp Implementer,,Mumbai,"Data Science, Recruitment, Salary"
38,Ankit Sinha,Head Analytics,,Indore,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
39,Gaurav Chouhan,Chief Technical Officer,,Bengaluru / Bangalore,"Software Development, Business Intelligence, B..."
40,Rashi Kacker,Sr Product Manager,,MYSORE,"Data Science, Node.js, Angularjs"
41,Ashwini,Director Global Delivery,,Hyderabad / Secunderabad,"Data Science, Media Marketing, Resource Planni..."
42,Balaji Kolli,Co Founder,,Bengaluru / Bangalore,"Data Analysis, Learning, Data Science, Compute..."
43,Rajani Nagaraj,HR Manager,,Mumbai,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
44,ROHIT Kumar,Architect,,Hyderabad / Secunderabad,"Software Development, Core Java, Unit Testing,..."
45,Amir Chowdhury,Managing Partner,,Noida,"Machine Learning, Data Science, Product Manage..."
46,SREEDHAR,Recruitment Consultant,,Mumbai,"Data Science, Machine Learning, Big Data Analy..."
47,Shailja Mishra,HR Manager,,Bengaluru / Bangalore,"consulting, Education Counseling, Educational ..."